(function () {
  // ══════════════════════════════════════════════════════════════
  //  YOUTUBE-STYLE SETTINGS POPUP — with Theme Picker sub-page
  // ══════════════════════════════════════════════════════════════

  const popupHTML = `
    <div id="settings-overlay" class="music-player-overlay" style="display:none;opacity:0;">
      <div class="music-player-card settings-card">
        <div class="music-close-btn" id="settings-close">&times;</div>

        <!-- ═══ PAGE: MAIN MENU ═══ -->
        <div class="settings-page" id="settings-main">
          <div class="settings-header">
            <div class="settings-title">Settings</div>
          </div>
          <div class="settings-content">

            <!-- Theme row — navigates to sub-page -->
            <div class="settings-menu-item" id="settings-theme-btn">
              <div class="settings-menu-left">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <circle cx="13.5" cy="6.5" r="2.5"/>
                  <path d="M17 2 A9 9 0 0 1 21 18"/>
                  <circle cx="6" cy="18" r="3"/>
                  <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10"/>
                </svg>
                <span>Theme</span>
              </div>
              <div class="settings-menu-right">
                <span class="settings-menu-value" id="settings-theme-current">Welkin</span>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                  <path d="m9 18 6-6-6-6"/>
                </svg>
              </div>
            </div>

            <div class="settings-divider"></div>

            <!-- Dark Mode toggle -->
            <div class="settings-menu-item">
              <div class="settings-menu-left">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
                </svg>
                <span>Dark Mode</span>
              </div>
              <label class="toggle-switch">
                <input type="checkbox" id="setting-darkmode">
                <span class="toggle-slider"></span>
              </label>
            </div>

            <!-- Cloak Mode toggle -->
            <div class="settings-menu-item">
              <div class="settings-menu-left">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
                  <circle cx="12" cy="12" r="3"/>
                </svg>
                <span>Cloak Mode</span>
              </div>
              <label class="toggle-switch">
                <input type="checkbox" id="setting-cloak">
                <span class="toggle-slider"></span>
              </label>
            </div>

            <!-- Background Music toggle -->
            <div class="settings-menu-item">
              <div class="settings-menu-left">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M9 18V5l12-2v13"/>
                  <circle cx="6" cy="18" r="3"/>
                  <circle cx="18" cy="16" r="3"/>
                </svg>
                <span>Background Music</span>
              </div>
              <label class="toggle-switch">
                <input type="checkbox" id="setting-music" checked>
                <span class="toggle-slider"></span>
              </label>
            </div>

          </div>
          <div class="settings-footer">
            <div class="settings-version">Welkin v1.0</div>
          </div>
        </div>

        <!-- ═══ PAGE: THEME PICKER ═══ -->
        <div class="settings-page settings-page-hidden" id="settings-themes">
          <div class="settings-subheader">
            <button class="settings-back-btn" id="settings-theme-back">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                <path d="m15 18-6-6 6-6"/>
              </svg>
            </button>
            <div class="settings-title">Theme</div>
          </div>
          <div class="settings-themes-grid" id="settings-themes-grid">
            <!-- Theme cards generated by JS -->
          </div>
        </div>

      </div>
    </div>
  `;

  const popupCSS = `
    /* ═══ CARD CONTAINER ═══ */
    .settings-card {
      flex-direction: column !important;
      padding: 0 !important;
      gap: 0 !important;
      width: 380px !important;
      max-width: 92vw;
      min-height: 420px;
      overflow: hidden;
      position: relative;
    }

    /* ═══ PAGE SYSTEM ═══ */
    .settings-page {
      display: flex;
      flex-direction: column;
      height: 100%;
      padding: 28px 24px 20px;
      transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1),
                  opacity 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    }
    .settings-page-hidden {
      display: none;
    }
    .settings-page-slide-left {
      animation: settingsSlideOutLeft 0.3s forwards;
    }
    .settings-page-slide-right {
      animation: settingsSlideInRight 0.3s forwards;
    }
    .settings-page-slide-back-left {
      animation: settingsSlideInLeft 0.3s forwards;
    }
    .settings-page-slide-back-right {
      animation: settingsSlideOutRight 0.3s forwards;
    }

    @keyframes settingsSlideOutLeft {
      from { transform: translateX(0); opacity: 1; }
      to   { transform: translateX(-40px); opacity: 0; }
    }
    @keyframes settingsSlideInRight {
      from { transform: translateX(40px); opacity: 0; }
      to   { transform: translateX(0); opacity: 1; }
    }
    @keyframes settingsSlideInLeft {
      from { transform: translateX(-40px); opacity: 0; }
      to   { transform: translateX(0); opacity: 1; }
    }
    @keyframes settingsSlideOutRight {
      from { transform: translateX(0); opacity: 1; }
      to   { transform: translateX(40px); opacity: 0; }
    }

    /* ═══ HEADER ═══ */
    .settings-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 20px;
    }
    .settings-subheader {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 20px;
    }
    .settings-title {
      font-size: 24px;
      font-weight: 800;
      color: #fff;
      font-family: 'Nunito', 'Inter', sans-serif;
      letter-spacing: -0.5px;
    }
    .settings-back-btn {
      width: 34px;
      height: 34px;
      border-radius: 50%;
      background: rgba(255,255,255,0.08);
      border: 1px solid rgba(255,255,255,0.12);
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      color: rgba(255,255,255,0.7);
      transition: all 0.2s;
    }
    .settings-back-btn:hover {
      background: rgba(255,255,255,0.15);
      color: #fff;
    }

    /* ═══ MENU ITEMS ═══ */
    .settings-content {
      flex: 1;
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .settings-menu-item {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 14px 16px;
      border-radius: 12px;
      cursor: pointer;
      transition: background 0.15s;
    }
    .settings-menu-item:hover {
      background: rgba(255,255,255,0.06);
    }
    .settings-menu-left {
      display: flex;
      align-items: center;
      gap: 14px;
      color: #fff;
      font-size: 15px;
      font-weight: 600;
    }
    .settings-menu-left svg {
      opacity: 0.6;
      flex-shrink: 0;
    }
    .settings-menu-right {
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .settings-menu-value {
      font-size: 13px;
      color: rgba(255,255,255,0.4);
      font-weight: 500;
    }
    .settings-menu-right svg {
      opacity: 0.3;
    }
    .settings-divider {
      height: 1px;
      background: rgba(255,255,255,0.06);
      margin: 4px 16px;
    }

    /* ═══ TOGGLE SWITCH ═══ */
    .toggle-switch {
      position: relative;
      width: 44px;
      height: 24px;
      flex-shrink: 0;
    }
    .toggle-switch input {
      opacity: 0;
      width: 0;
      height: 0;
    }
    .toggle-slider {
      position: absolute;
      cursor: pointer;
      inset: 0;
      background: rgba(255,255,255,0.15);
      border-radius: 24px;
      transition: 0.3s;
    }
    .toggle-slider:before {
      content: '';
      position: absolute;
      height: 18px;
      width: 18px;
      left: 3px;
      bottom: 3px;
      background: white;
      border-radius: 50%;
      transition: 0.3s;
    }
    .toggle-switch input:checked + .toggle-slider {
      background: #3A8FE0;
    }
    .toggle-switch input:checked + .toggle-slider:before {
      transform: translateX(20px);
    }

    /* ═══ FOOTER ═══ */
    .settings-footer {
      padding-top: 16px;
      border-top: 1px solid rgba(255,255,255,0.06);
      text-align: center;
    }
    .settings-version {
      font-size: 12px;
      color: rgba(255,255,255,0.2);
    }

    /* ═══ THEME CARDS GRID ═══ */
    .settings-themes-grid {
      display: flex;
      flex-direction: column;
      gap: 8px;
      overflow-y: auto;
      max-height: 380px;
      padding-right: 4px;
    }
    .theme-card {
      display: flex;
      align-items: center;
      gap: 14px;
      padding: 14px 16px;
      border-radius: 14px;
      cursor: pointer;
      border: 1.5px solid rgba(255,255,255,0.08);
      background: rgba(255,255,255,0.03);
      transition: all 0.2s;
      position: relative;
    }
    .theme-card:hover {
      background: rgba(255,255,255,0.07);
      border-color: rgba(255,255,255,0.15);
      transform: translateY(-1px);
    }
    .theme-card.active {
      border-color: rgba(108,180,240,0.5);
      background: rgba(58,143,224,0.1);
    }

    /* Gradient preview strip */
    .theme-preview {
      width: 48px;
      height: 48px;
      border-radius: 12px;
      flex-shrink: 0;
      position: relative;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0,0,0,0.3);
    }

    .theme-info {
      flex: 1;
      min-width: 0;
    }
    .theme-name {
      font-size: 15px;
      font-weight: 700;
      color: #fff;
      margin-bottom: 2px;
      display: flex;
      align-items: center;
      gap: 6px;
    }
    .theme-name-emoji {
      font-size: 16px;
    }
    .theme-desc {
      font-size: 12px;
      color: rgba(255,255,255,0.35);
      font-weight: 400;
    }

    /* Checkmark on active theme */
    .theme-check {
      width: 24px;
      height: 24px;
      border-radius: 50%;
      border: 2px solid rgba(255,255,255,0.12);
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      transition: all 0.2s;
    }
    .theme-card.active .theme-check {
      background: #3A8FE0;
      border-color: #3A8FE0;
    }
    .theme-check svg {
      opacity: 0;
      transition: opacity 0.2s;
    }
    .theme-card.active .theme-check svg {
      opacity: 1;
    }
  `;

  // ══════════════════════════════════════════════════════════════
  //  INIT
  // ══════════════════════════════════════════════════════════════

  function init() {
    const style = document.createElement("style");
    style.textContent = popupCSS;
    document.head.appendChild(style);

    document.body.insertAdjacentHTML("beforeend", popupHTML);

    const overlay = document.getElementById("settings-overlay");
    const closeBtn = document.getElementById("settings-close");
    const mainPage = document.getElementById("settings-main");
    const themesPage = document.getElementById("settings-themes");
    const themeBtn = document.getElementById("settings-theme-btn");
    const backBtn = document.getElementById("settings-theme-back");
    const currentLabel = document.getElementById("settings-theme-current");
    const grid = document.getElementById("settings-themes-grid");

    // ── Build theme cards ─────────────────────────────────────
    function buildThemeCards() {
      if (!window.welkinThemes) return;
      grid.innerHTML = "";
      const themes = window.welkinThemes.list();
      const current = window.welkinThemes.current();

      themes.forEach(t => {
        const card = document.createElement("div");
        card.className = "theme-card" + (t.id === current ? " active" : "");
        card.dataset.themeId = t.id;

        // Build gradient from preview colors
        const gradient = `linear-gradient(135deg, ${t.preview[0]} 0%, ${t.preview[1]} 33%, ${t.preview[2]} 66%, ${t.preview[3]} 100%)`;

        card.innerHTML = `
          <div class="theme-preview" style="background: ${gradient}"></div>
          <div class="theme-info">
            <div class="theme-name">
              <span class="theme-name-emoji">${t.emoji}</span>
              ${t.name}
            </div>
            <div class="theme-desc">${t.desc}</div>
          </div>
          <div class="theme-check">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="20 6 9 17 4 12"/>
            </svg>
          </div>
        `;

        card.addEventListener("click", () => {
          if (window.welkinThemes) {
            window.welkinThemes.apply(t.id);
            // Update UI
            grid.querySelectorAll(".theme-card").forEach(c => c.classList.remove("active"));
            card.classList.add("active");
            currentLabel.textContent = t.name;
          }
        });

        grid.appendChild(card);
      });

      // Update current label
      const currentTheme = themes.find(t => t.id === current);
      if (currentTheme) currentLabel.textContent = currentTheme.name;
    }

    // ── Navigation between pages ──────────────────────────────
    function showThemesPage() {
      buildThemeCards();
      mainPage.classList.add("settings-page-slide-left");
      setTimeout(() => {
        mainPage.classList.add("settings-page-hidden");
        mainPage.classList.remove("settings-page-slide-left");
        themesPage.classList.remove("settings-page-hidden");
        themesPage.classList.add("settings-page-slide-right");
        setTimeout(() => {
          themesPage.classList.remove("settings-page-slide-right");
        }, 300);
      }, 280);
    }

    function showMainPage() {
      themesPage.classList.add("settings-page-slide-back-right");
      setTimeout(() => {
        themesPage.classList.add("settings-page-hidden");
        themesPage.classList.remove("settings-page-slide-back-right");
        mainPage.classList.remove("settings-page-hidden");
        mainPage.classList.add("settings-page-slide-back-left");
        setTimeout(() => {
          mainPage.classList.remove("settings-page-slide-back-left");
        }, 300);
      }, 280);
    }

    themeBtn.addEventListener("click", showThemesPage);
    backBtn.addEventListener("click", showMainPage);

    // ── Open / close popup ────────────────────────────────────
    function resetToMainPage() {
      themesPage.classList.add("settings-page-hidden");
      themesPage.classList.remove("settings-page-slide-right", "settings-page-slide-back-right");
      mainPage.classList.remove("settings-page-hidden", "settings-page-slide-left", "settings-page-slide-back-left");
    }

    window.toggleSettings = () => {
      if (
        overlay.style.display === "none" ||
        !overlay.classList.contains("open")
      ) {
        resetToMainPage();
        // Update current theme label
        if (window.welkinThemes) {
          const themes = window.welkinThemes.list();
          const current = window.welkinThemes.current();
          const currentTheme = themes.find(t => t.id === current);
          if (currentTheme) currentLabel.textContent = currentTheme.name;
        }
        overlay.classList.add("open");
        overlay.style.display = "flex";
        setTimeout(() => (overlay.style.opacity = "1"), 10);
      } else {
        closePopup();
      }
    };

    const closePopup = () => {
      overlay.style.opacity = "0";
      setTimeout(() => {
        overlay.classList.remove("open");
        overlay.style.display = "none";
      }, 300);
    };

    closeBtn.onclick = closePopup;
    overlay.onclick = (e) => {
      if (e.target === overlay) closePopup();
    };

    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") {
        if (overlay.classList.contains("open")) {
          closePopup();
        }
      }
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
